### ISSUE TITLE
is Linux development flow broken? couldn't build local app

### ISSUE THREAD

**Issue by infinite-spectrum** [johnlindquist/kitapp#197]
I was trying to build kitapp locally on linux (ubuntu) and it was not straight forward. After tweakig certain things reached to a place where getting below message:
Error: Cannot find module '@johnlindquist/kit/cjs/enum'
Require stack:
- /home/apurva/dev/kitapp/src/main.dev.ts
- /home/apurva/dev/kitapp/node_modules/electron/dist/resources/default_app.asar/main.js

Is there any guide, which can help me setup scriptkit locally?

**Comment by johnlindquist** [comment]
I'm traveling today. I'll write up a guide tomorrow. It's a bit more than I can type out on my phone

**Comment by infinite-spectrum** [comment]
@johnlindquist waiting for your response.

**Comment by johnlindquist** [comment]
Dang, I missed my reminder to respond to you.

I wrote up the setup guide into the main README.md:

https://github.com/johnlindquist/kit

If you'd like more real-time help, we're starting up a discord where we can do more dev chat. I'd be happy to help you out there:

https://discord.gg/DsygUuDK

**Comment by infinite-spectrum** [comment]
Thank you  @johnlindquist.
